export const stepOneField = [{
        id: 1,
        name: "shopName",
        label: "Your Shop name",
        type: "text",
        required: true,
        helpBlock: "Please Enter In Here Your Store Name,This how customer locates you. e.g Fendi Store, Gucci ",
    },
    {
        id: 2,
        name: "Product_Category",
        label: "Your Shop Category",
        type: "text",
        required: true,
        helpBlock: "What category will you  classify your store. e.g Agriculture, Medicine etc",
    },
    {
        id: 3,
        name: "AddressLine1",
        label: "Shop Address",
        type: "text",
        required: true,
        helpBlock: "Your physical store address, block or house number, street name, nearest street",
    },
    {
        id: 4,
        name: "AddressLine2",
        label: "closest landmark, P.O box",
        type: "text",
        helpBlock: "e.g beside Landmark A, P.O box 1234A",
    },
    {
        id: 5,
        name: "cityOrTown",
        label: "City Or Town",
        type: "text",
        required: true,
        helpBlock: "Festac",
    },
];

export const stepTwoField = [{
        id: 1,
        name: "TIN",
        label: "TIN",
        type: "text",
        required: false,
        helpBlock: "Your tax identification number",
    },
    {
        id: 2,
        name: "BusinessRegistration",
        label: "CAC Registration Number",
        type: "text",
        helpBlock: "Your CAC registration number",
    },
    {
        id: 3,
        name: "VATRegistrationStatus",
        label: "VAT registration status",
        type: "text",
        helpBlock: "Chose registered if you have completed the VAT registration",
    },
];